{
 "title": "Kafka Dashboard",
 "tags": [ "kafka" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "kafka_job_name",
    "label": "kafka_job_name",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_replicamanager_leadercount{job=\"$kafka_job_name\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_messagesinpersec_one_minute_rate{job=\"$kafka_job_name\", topic!=\"\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=\"$kafka_job_name\", instance=~\"$broker\"}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_globaltopiccount{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Under Replicated",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_globalpartitioncount{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=\"$kafka_job_name\"})"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_messagesinpersec_one_minute_rate{job=\"$kafka_job_name\", topic=~\"$topic\", topic!=\"\"}) by (broker, topic, node_id)",
     "legendFormat": "(broker=\"{{broker}}\", job=\"kafka-broker\", node_id=\"{{node_id}}\")"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesinpersec_one_minute_rate{job=\"$kafka_job_name\", topic=~\"$topic\", topic!=\"\"}) by (broker, topic, node_id)",
     "legendFormat": "(broker=\"{{broker}}\", job=\"kafka-broker\", node_id=\"{{node_id}}\")"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesoutpersec_one_minute_rate{job=\"$kafka_job_name\", topic=~\"$topic\", topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"$kafka_job_name\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{job=\"$kafka_job_name\", instance=~\"$broker\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_server_zookeeperrequestlatencyms_total{job=\"$kafka_job_name\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeeperexpirespersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_zookeedisconnectspersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum by (consumergroup, topic) (kafka_consumergroup_lag{job=\"kafka-exporter\"})",
     "legendFormat": "{{consumergroup}} / {{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_isrexpandspersec_one_minute_rate{job=\"$kafka_job_name\", instance=~\"$broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_underreplicated{job=\"$kafka_job_name\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}