CREATE TABLE IF NOT EXISTS settlement_policy
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id         BIGINT      NOT NULL,
    pg_fee_rate       INTEGER     NOT NULL CHECK (pg_fee_rate >= 0 AND pg_fee_rate <= 10000),
    platform_fee_rate INTEGER     NOT NULL CHECK (platform_fee_rate >= 0 AND platform_fee_rate <= 10000),
    settlement_cycle  VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    min_payout_amount BIGINT      NOT NULL DEFAULT 0 CHECK (min_payout_amount >= 0),
    status            VARCHAR(15) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at       TIMESTAMP
);

-- 활성 정산 정책은 판매자당 1건만 존재 (소프트 삭제를 고려한 partial unique index)
CREATE UNIQUE INDEX IF NOT EXISTS idx_settlement_policy_seller_active
    ON settlement_policy (seller_id) WHERE status = 'ACTIVE';

-- 판매자 ID 조회용 인덱스
CREATE INDEX IF NOT EXISTS idx_settlement_policy_seller_id
    ON settlement_policy (seller_id);
