global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: 'shop-user'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'users.marketnote.store:443'
        labels:
          service: 'user-service'

  - job_name: 'shop-product'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'products.marketnote.store:443'
        labels:
          service: 'product-service'

  - job_name: 'shop-commerce'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'commerce.marketnote.store:443'
        labels:
          service: 'commerce-service'

  - job_name: 'shop-community'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'community.marketnote.store:443'
        labels:
          service: 'community-service'

  - job_name: 'marketnote'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'rewards.marketnote.store:443'
        labels:
          service: 'reward-service'

  - job_name: 'shop-fulfillment'
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets:
          - '${FULFILLMENT_PRIVATE_IP}:8080'
        labels:
          service: 'fulfillment-service'
    relabel_configs:
      - source_labels: []
        target_label: instance
        replacement: 'fulfillment.marketnote.store:8080'

  - job_name: 'shop-file'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets:
          - 'files.marketnote.store:443'
        labels:
          service: 'file-service'

  - job_name: 'kafka-broker'
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 30s
    static_configs:
      - targets:
          - '${KAFKA_BROKER_1_PRIVATE_IP}:7071'
        labels:
          broker: 'broker-1'
          node_id: '1'
      - targets:
          - '${KAFKA_BROKER_2_PRIVATE_IP}:7071'
        labels:
          broker: 'broker-2'
          node_id: '2'
      - targets:
          - '${KAFKA_BROKER_3_PRIVATE_IP}:7071'
        labels:
          broker: 'broker-3'
          node_id: '3'

  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    scheme: http
    scrape_interval: 30s
    static_configs:
      - targets:
          - '${KAFKA_BROKER_1_PRIVATE_IP}:9308'
