package com.personal.marketnote.fulfillment.mapper;

import com.personal.marketnote.common.kafka.event.FulfillmentGoodsSyncedEvent;
import com.personal.marketnote.fulfillment.port.in.command.vendor.RegisterFulfillmentGoodsItemCommand;
import com.personal.marketnote.fulfillment.port.in.command.vendor.UpdateFulfillmentGoodsItemCommand;

import java.util.List;

public class FulfillmentGoodsSyncedEventMapper {

    private FulfillmentGoodsSyncedEventMapper() {
    }

    public static FulfillmentGoodsSyncedEvent mapToEvent(RegisterFulfillmentGoodsItemCommand item) {
        return new FulfillmentGoodsSyncedEvent(
                item.productCode(),
                null,
                item.productName(),
                item.productType(),
                null,
                item.inventoryProductNameUseYn(),
                item.productOptionCode1(),
                item.productOptionCode2(),
                null,
                null,
                item.supplierCode(),
                null,
                item.categoryCode(),
                null,
                item.seasonCode(),
                item.genderCode(),
                item.productPrice(),
                item.inboundPrice(),
                item.salePrice(),
                item.dealTemperature(),
                item.pickFactor(),
                item.giftDivision(),
                null,
                null,
                null,
                null,
                item.manufactureYear(),
                null,
                null,
                null,
                null,
                item.productBarcode(),
                null,
                null,
                null,
                null,
                item.boxWeight(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                item.origin(),
                item.expirationManagementYn(),
                item.shelfLifeDays(),
                item.outboundCancelDays(),
                item.inboundCancelDays(),
                item.boxDivision(),
                item.bufferProductYn(),
                item.loadingDirection(),
                null,
                item.useYn(),
                item.feeYn(),
                item.saleUnitQuantity(),
                null,
                item.safetyStock(),
                List.of()
        );
    }

    public static FulfillmentGoodsSyncedEvent mapToEvent(UpdateFulfillmentGoodsItemCommand item) {
        return new FulfillmentGoodsSyncedEvent(
                item.productCode(),
                null,
                item.productName(),
                item.productType(),
                null,
                item.inventoryProductNameUseYn(),
                item.productOptionCode1(),
                item.productOptionCode2(),
                null,
                null,
                item.supplierCode(),
                null,
                item.categoryCode(),
                null,
                item.seasonCode(),
                item.genderCode(),
                item.productPrice(),
                item.inboundPrice(),
                item.salePrice(),
                item.dealTemperature(),
                item.pickFactor(),
                item.giftDivision(),
                null,
                null,
                null,
                null,
                item.manufactureYear(),
                null,
                null,
                null,
                null,
                item.productBarcode(),
                null,
                null,
                null,
                null,
                item.boxWeight(),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                item.origin(),
                item.expirationManagementYn(),
                item.shelfLifeDays(),
                item.outboundCancelDays(),
                item.inboundCancelDays(),
                item.boxDivision(),
                item.bufferProductYn(),
                item.loadingDirection(),
                null,
                item.useYn(),
                item.feeYn(),
                item.saleUnitQuantity(),
                null,
                item.safetyStock(),
                List.of()
        );
    }
}
